name = "TauRunner"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Ibrahim Safa", "Carlos A. Arguelles", "Jeff Lazar", "Alex Pizzuto"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
PROPOSAL = "0dd74e74-b753-4f0a-bbfe-831cdbe783b0"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ArgParse = "1"
Interpolations = "0.14, 0.15"
JLD2 = "0.4, 0.5"
JSON3 = "1"
LRUCache = "1"
NPZ = "0.4"
QuadGK = "2"
Roots = "2"
StaticArrays = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[targets]
test = ["Test", "Statistics"]
